apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-admin-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  KEYCLOAK_USER: {{ .Values.keycloakAdminUser | b64enc }}
  KEYCLOAK_PASSWORD: {{ .Values.keycloakAdminPassword | b64enc }}